### ISSUE TITLE
External module issue

### ISSUE THREAD

**Issue by edsrzf** [goto-bus-stop/browser-pack-flat#40]
I'm running into an issue when using external modules, such as when splitting code into separate app and dependency bundles.

Consider a trivial "Hello, world!" React application:

```js
const React = require('react');
const ReactDOM = require('react-dom');

ReactDOM.render(
  React.createElement('h1', null, 'Hello, World!'),
  document.getElementById('root')
);
```

(I'm not using JSX syntax to avoid needing Babel.)

Bundle with Browserify (with or without `browser-pack-flat`) works great:

```sh
# works
browserify index.js -o app.js
# also works
browserify -p browser-pack-flat index.js -o app.js
```

Now imagine I want to externalize `react` and `react-dom` to keep dependencies separate, so I run:

```sh
browserify -p browser-pack-flat -r react -r react-dom -o vendor.js
browserify -p browser-pack-flat -x react -x react-dom index.js -o app.js
```

The bundles no longer work correctly. In a browser, after including both `vendor.js` and `app.js`, in that order, I get a console error:

```
Uncaught TypeError: React.createElement is not a function
```

If I take a look at the value of the `React` variable through the debugger, it's a function with no additional properties. If I call it with no arguments, it returns an object that contains the properties I'd expect the `React` variable to have (`createElement`, `createContext`, `memo`, etc.).

The same Browserify commands work fine if I exclude `-p browser-pack-flat`.

Browserify version: 16.2.3
browser-flat-pack version: 3.4.1 (also tried 3.4.0)

I tried browser-flat-pack 3.3.0 and it worked correctly, so it appears this has regressed since that release. (Which included a fix for another one of my bugs in #36. 😅)

I'm working on finding a reduced test case for this that doesn't involve such large dependencies, but thought I'd go ahead and file this since it definitely seems like a bug to me.

**Comment by edsrzf** [comment]
I think this was introduced in #37.

If I try commit 305ed59cdef2a7343ae47fe3758ce0167bf78b97, just before #37 was merged, things worked fine.

If I try commit be24dafca8c3ae0d7280a53a8ab4a63f7a9c018f, after #37, it's broken.

There is no difference between the two versions in `app.js`, so it's only a difference in how the external modules are exposed.

**Comment by goto-bus-stop** [comment]
Oh, perhaps that PR broke this `module.exports` pattern that React uses:
https://unpkg.com/react@16.8.6/index.js
```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react.production.min.js');
} else {
  module.exports = require('./cjs/react.development.js');
}
```

**Comment by goto-bus-stop** [comment]
Most likely the bug occurs when exposing a module that is 'lazily' evaluated rather than fully inlined, since the value of `require('react')` is now the internal lazy evaluation wrapper function. The change in #37 turned react's index.js file from an inlined module to a 'lazy' module.

![image](https://user-images.githubusercontent.com/1006268/58787494-36381f80-85ea-11e9-97b6-68a28efd1991.png)

**Comment by edsrzf** [comment]
If I'm reading things right then I think the issue is that `exposedRequire` just returns the function for the lazily-evaluated module rather than calling it and returning the result of the call.

Today we have:

```
exposedRequire.m["react"] = _$react_react;
```

One option would be for lazily-evaluated modules to define getters like:

```
Object.defineProperty(exposedRequire.m, "react", { get: function() { return _$react_react(); }});
```

Then no changes would need to be made to `exposedRequire`. (I tried modifying the `browser-pack-flat` to generate this and it seems to work. Happy to create a pull request if you think this is a good way forward.)

Another option would be to somehow mark modules that are lazily-evaluated and treat them differently when they're `require`d.
